server:
  port: 8080
spring:
  application:
    name: REST-TEMPLATE-CLIENT
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}