server:
  port: 8080
spring:
  application:
    name: mongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
logging:
  level:
    org.springframework.data: debug
